import { Metadata } from 'next';


export const metadata: Metadata = {
  title: 'Clinic Services',
};

export default function Page() {
    return <p className='m-20 p-10'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh mauris cursus mattis molestie a iaculis at erat. Nulla facilisi etiam dignissim diam quis enim. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt tortor. In ante metus dictum at tempor commodo. Semper eget duis at tellus. Ac orci phasellus egestas tellus rutrum tellus pellentesque. Ipsum consequat nisl vel pretium lectus. Odio facilisis mauris sit amet massa. Id porta nibh venenatis cras sed felis eget velit aliquet. Eros in cursus turpis massa tincidunt dui. Ultrices vitae auctor eu augue. Placerat orci nulla pellentesque dignissim enim sit amet venenatis. Vitae suscipit tellus mauris a diam maecenas sed enim. Quam elementum pulvinar etiam non quam lacus. Quis imperdiet massa tincidunt nunc pulvinar. Ut pharetra sit amet aliquam id diam maecenas ultricies. Aliquet lectus proin nibh nisl condimentum id venenatis a condimentum. Fringilla urna porttitor rhoncus dolor. Odio tempor orci dapibus ultrices in iaculis nunc sed augue. Lectus urna duis convallis convallis tellus id. Est velit egestas dui id ornare arcu odio ut sem. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Congue nisi vitae suscipit tellus.Orci a scelerisque purus semper eget. Aenean sed adipiscing diam donec adipiscing tristique risus nec feugiat. Ipsum consequat nisl vel pretium. Vulputate dignissim suspendisse in est ante in nibh. Nunc eget lorem dolor sed. At varius vel pharetra vel turpis nunc eget lorem dolor. Diam in arcu cursus euismod quis viverra nibh cras. Sagittis vitae et leo duis ut diam quam. Pellentesque habitant morbi tristique senectus et. Justo donec enim diam vulputate ut pharetra sit amet. Nec tincidunt praesent semper feugiat nibh sed pulvinar. Arcu vitae elementum curabitur vitae.</p>;
  }